---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-databases-job
spec:
  template:
    spec:
      containers:
      - name: create-databases
        image: postgres:latest
        env:
        - name: PGPASSWORD
          value: "mysecretpassword"
        command: ["/bin/sh", "-c", "until pg_isready -h postgres -U postgres; do echo waiting for database; sleep 2; done; psql -h postgres -U postgres -c 'CREATE DATABASE userdb;'"]
      restartPolicy: OnFailure